// <auto-generated />
using Autosave.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Autosave.Migrations
{
    [DbContext(typeof(AutosaveDbContext))]
    [Migration("20180214124405_Autosave")]
    partial class Autosave
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Autosave.Models.Device", b =>
                {
                    b.Property<string>("FunctionalLocationNumber")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConfigurationSoftware");

                    b.Property<string>("Description");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Manufacturer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("FunctionalLocationNumber");

                    b.ToTable("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
